# Home work #1

## Тема “Вычисления с помощью Numpy”

#### Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.<br>
Создайте массив Numpy под названием "__a__" размером 5x2, то есть состоящий из 5 строк и 2 столбцов.<br>
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. <br>Будем считать, что каждый столбец - это признак, а строка - наблюдение. <br>Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. <br>Результат запишите в массив __mean_a__, в нем должно быть 2 элемента.

In [1]:
import numpy as np

In [2]:
a = np.array([
    [1, 2, 3, 3, 1],
    [1, 2, 3, 3, 1]
]).transpose()
a

array([[1, 1],
       [2, 2],
       [3, 3],
       [3, 3],
       [1, 1]])

In [3]:
mean_a = np.array([np.mean(a[:,0]), np.mean(a[:,1])])
mean_a

array([2., 2.])

#### Задание 2
Вычислите массив __a_centered__, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве __mean_a__. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [4]:
a_centered = a - mean_a
a_centered

array([[-1., -1.],
       [ 0.,  0.],
       [ 1.,  1.],
       [ 1.,  1.],
       [-1., -1.]])

#### Задание 3
Найдите скалярное произведение столбцов массива __a_centered__. В результате должна получиться величина a_centered_sp. <br>
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [5]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])
a_centered_sp

4.0

In [6]:
cov1 = a_centered_sp / (len(a_centered)-1)
cov1

1.0

##### Задание 4**
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.

Подробнее узнать о ковариации можно здесь:<br>
https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html <br>
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции *np.cov*. <br>В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. <br>В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [7]:
#ковариационная матрица
m = np.cov(a.transpose())
m

array([[1., 1.],
       [1., 1.]])

In [8]:
cov2 = m[0,1]
cov2

1.0

In [9]:
cov1 == cov2

True

************************************************************************************************************************
************************************************************************************************************************

## Тема “Работа с данными в Pandas”

#### Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd.<br>
Создайте датафрейм __authors__ со столбцами author_id и author_name, в которых соответственно содержатся данные:
- [1, 2, 3]
- ['Тургенев', 'Чехов', 'Островский'].<br><br>
Затем создайте датафрейм __books__ cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
- [1, 1, 1, 2, 2, 3, 3],
- ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
- [450, 300, 350, 500, 450, 370, 290].

In [10]:
import pandas as pd

In [11]:
authors = pd.DataFrame({
    'author_id': [1, 2, 3] ,
    'author_name': ['Тургенев', 'Чехов', 'Островский']})

In [12]:
books = pd.DataFrame({
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [450, 300, 350, 500, 450, 370, 290]})

In [13]:
authors.head()

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [14]:
books.head()

author_id         book_title  price
0          1        Отцы и дети    450
1          1              Рудин    300
2          1  Дворянское гнездо    350
3          2   Толстый и тонкий    500
4          2    Дама с собачкой    450

#### Задание 2
Получите датафрейм __authors_price__, соединив датафреймы __authors__ и __books__ по полю author_id.

In [15]:
authors_price = pd.merge(authors, books, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

#### Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [16]:
top5 = authors_price.sort_values(by='price', ascending=False).head()
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

#### Задание 4
Создайте датафрейм __authors_stat__ на основе информации из authors_price.<br>
В датафрейме __authors_stat__ должны быть четыре столбца:
- author_name,
- min_price,
- max_price
- mean_price,<br>
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [17]:
maxx = authors_price.groupby('author_name').agg({'price': 'max'})
minn = authors_price.groupby('author_name').agg({'price': 'min'})
mean = authors_price.groupby('author_name').agg({'price': 'mean'})

In [18]:
x = pd.merge(maxx, minn, on='author_name', how='inner')
authors_stat = pd.merge(x, mean, on='author_name', how='inner')
authors_stat = authors_stat.rename(columns = {'price_x': 'min_price', 'price_y': 'max_price', 'price': 'mean_price'})
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         370        290  330.000000
Тургенев           450        300  366.666667
Чехов              500        450  475.000000

#### Задание 5**
Создайте новый столбец в датафрейме __authors_price__ под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. <br>
В этот столбец поместите данные из следующего списка:<br>
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].<br>
Просмотрите документацию по функции *pd.pivot_table* с помощью вопросительного знака. <br>
Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
<br>Назовите полученный датасет __book_info__ и сохраните его в формат *pickle* под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его __book_info2__. Удостоверьтесь, что датафреймы __book_info__ и __book_info2__ идентичны.


In [19]:
?pd.pivot_table

In [20]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [21]:
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [22]:
book_info = pd.pivot_table(
    authors_price,
    values='price',
    index='author_name',
    columns='cover',
    aggfunc='mean',
    fill_value=0
)
book_info

cover        мягкая  твердая
author_name                 
Островский      330        0
Тургенев        325      450
Чехов             0      475

In [23]:
book_info.to_pickle('book_info2.pkl')

In [24]:
book_info2 = pd.read_pickle('book_info2.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский      330        0
Тургенев        325      450
Чехов             0      475